title: "Intro to BTI"
description: "A walkthrough on what BTI is and why it is crucial for hardware security and semiconductor reliability research."
baseurl: "/intro2bti"
url: "https://adityabedekar17.github.io/"
remote_theme: just-the-docs/just-the-docs
color_scheme: nil
search_enabled: true
nav_sort: order

plugins:
  - jekyll-seo-tag
  -  jekyll-remote-theme
footer_content: "Built by <a href='/intro2bti/docs/cite'>Aditya Ashish Bedekar</a> &middot; Advised by   
<a href='https://www.dustinrichmond.com/'>Dr. Dustin Richmond</a> &middot; <a href='/intro2bti/docs/cite'>Cite this resource</a> &middot; Last updated: April 2026"
